export const images = [
	"images/cards/Watermelon.png",
	"images/cards/Starfish.png",
	"images/cards/Galgal.png",
	"images/cards/Tree.png",
	"images/cards/Flamingo.png",
	"images/cards/Map.png",
	"images/cards/Leaf.png",
	"images/cards/Snapirim.png",
	"images/cards/Flower.png",
	"images/cards/FlipFlops.png",
	"images/cards/Sunglasses.png",
	"images/cards/Popsicle.png",
	"images/cards/Lemonade.png",
	"images/cards/Castle.png",
	"images/cards/Snorkling.png",
	"images/cards/BeachSign.png",
	"images/cards/Sunscreen.png",
	"images/cards/Sun.png",
	"images/cards/Shell.png",
	"images/cards/Octopus.png",
	"images/cards/Turtle.png",
	"images/cards/Plane.png",
	"images/cards/Tikki.png",
	"images/cards/Pool.png",
	"images/cards/Floatie.png",
	"images/cards/Chair.png",
    "images/cards/Crab.png",
    "images/cards/Postcards.png",
    "images/cards/HawaiianShirt.png",
    "images/cards/Pineapple.png",
    "images/cards/IceCream.png",
    "images/cards/Shark.png",
    "images/cards/Coconut.png",
    "images/cards/WaterPistol.png",
    "images/cards/Bucket.png",
	"images/cards/Sunhat.png",
	"images/cards/Conch.png",
	"images/cards/MessageInBottle.png",
	"images/cards/Surf.png",
];

export const audio = {
	click: new Audio("sounds/mixkit-game-ball-tap-2073.wav"),
	flip: new Audio("sounds/420686-Card-Game-Movement-Deal-Single-Whoosh-Light-02.wav"),
	match: new Audio("sounds/mixkit-video-game-treasure-2066.wav"),
	win: new Audio("sounds/mixkit-completion-of-a-level-2063.wav"),
	background: new Audio("sounds/cute-creatures-150622.mp3")
};